// Generates the two tables that connect interpreted Lean code with the runtime:
//
//  * ExternTable.g.cs: for every `@[extern "sym"]` declaration in the IR of Init/Std/Lean whose
//    symbol is a static method of the runtime, a wrapper taking the arguments from the caller's
//    frame (externs without such a method are forwarded to `@[export sym]` functions at run time,
//    or reported as missing);
//  * ExportStubs.g.cs: for every `@[export sym]` function, an entry point with its C signature
//    that runs the function in the interpreter (the runtime and the kernel call these).
//
// usage: GenTables <sysroot> [<output directory>]

using System.Reflection;
using System.Text;
using LeanInterpreter.Runtime;
using LeanInterpreter.Runtime.Compact;
using static LeanInterpreter.Runtime.LeanRt;

if (args.Length < 1)
{
    Console.Error.WriteLine("usage: GenTables <sysroot> [<output directory>]");
    return 1;
}
string libDir = Path.Combine(args[0], "lib", "lean");
string outDir = args.Length > 1 ? args[1] : Path.Combine(AppContext.BaseDirectory, "../../../../../src/LeanInterpreter/Interp");

var externs = new SortedDictionary<string, (string[] Params, string Ret, string Decl)>(StringComparer.Ordinal);
var exports = new SortedDictionary<string, string>(StringComparer.Ordinal);
var decls = new Dictionary<string, Obj>();
foreach (var root in new[] { "Init", "Std", "Lean" })
{
    var files = Directory.EnumerateFiles(libDir, root + ".olean")
        .Concat(Directory.EnumerateFiles(Path.Combine(libDir, root), "*.olean", SearchOption.AllDirectories));
    foreach (var olean in files)
    {
        var main = OleanFile.Read(olean);
        var data = main;
        if (File.Exists(olean + ".private"))
            data = OleanFile.Read(olean + ".private", main, OleanFile.Read(olean + ".server", main));
        foreach (var (ext, arr) in Entries(data.Root))
            if (ext == "Lean.exportAttr")
                foreach (var x in arr) exports[Name(lean_ctor_get(x, 1))] = Name(lean_ctor_get(x, 0));
        var ir = Path.ChangeExtension(olean, ".ir");
        if (!File.Exists(ir)) continue;
        foreach (var (ext, arr) in Entries(OleanFile.Read(ir, OleanFile.Read(ir + ".sig")).Root))
        {
            if (ext != "Lean.IR.declMapExt") continue;
            foreach (var d in arr)
            {
                decls[Name(lean_ctor_get(d, 0))] = d;
                if (lean_obj_tag(d) != 1) continue; // Decl.extern
                var sym = ExternSymbol(lean_ctor_get(d, 3));
                if (sym == null) continue;
                var ps = Arr(lean_ctor_get(d, 1)).Select(p => Ty(lean_ctor_get(p, 1))).ToArray();
                externs.TryAdd(sym, (ps, Ty(lean_ctor_get(d, 2)), Name(lean_ctor_get(d, 0))));
            }
        }
    }
}

// ----------------------------------------------------------------------
// ExternTable.g.cs

var methods = typeof(Obj).Assembly.GetTypes()
    .Where(t => t.Namespace is "LeanInterpreter.Runtime" or "LeanInterpreter.Kernel")
    .SelectMany(t => t.GetMethods(BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.DeclaredOnly))
    .Where(m => !m.IsGenericMethodDefinition && !m.IsSpecialName && m.ReturnType != typeof(void))
    .GroupBy(m => m.Name).ToDictionary(g => g.Key, g => g.ToList());
var wrappers = new StringBuilder();
var reg = new StringBuilder();
var notInRuntime = new List<string>();
foreach (var (sym, (ps, ret, decl)) in externs)
{
    var live = ps.Where(p => p != "irr" && p != "void").ToArray();
    var mi = methods.TryGetValue(sym, out var cands) ? cands.FirstOrDefault(m => m.GetParameters().Length == live.Length) : null;
    string call = null;
    if (mi != null)
    {
        var mps = mi.GetParameters();
        var argExprs = live.Select((t, i) => Conv(t, mps[i].ParameterType, $"A(s, b, a[{i}])")).ToList();
        if (argExprs.All(e => e != null))
            call = Ret(ret, mi.ReturnType, $"{mi.DeclaringType.FullName.Replace('+', '.')}.{mi.Name}({string.Join(", ", argExprs)})");
    }
    if (call == null) { notInRuntime.Add($"{sym} ({decl})"); continue; }
    wrappers.Append($"    static Value {sym}(Value[] s, int b, int[] a) => {call};\n");
    reg.Append($"        t[\"{sym}\"] = (nint)(delegate*<Value[], int, int[], Value>)&{sym};\n");
}
File.WriteAllText(Path.Combine(outDir, "ExternTable.g.cs"), $$"""
    // <auto-generated by tools/GenTables/>
    // Calls from interpreted code to the runtime functions that implement `@[extern]` declarations
    // of Init/Std/Lean, generated from the extern declarations of the sysroot's `.ir` files and the
    // runtime's method signatures. Arguments are the non-erased parameters, in order, read from
    // the caller's frame `s` at base `b` (slots `a`, see `ExternTable.A`).

    using LeanInterpreter.Runtime;

    namespace LeanInterpreter.Interp;

    internal static unsafe partial class ExternTable
    {
        static void RegisterGenerated(Dictionary<string, nint> t)
        {
    {{reg}}    }

    {{wrappers}}}

    """.Replace("\r\n", "\n"));
Console.WriteLine($"{externs.Count} extern symbols, {externs.Count - notInRuntime.Count} implemented by the runtime; not in the runtime (forwarded to an export or unsupported):");
foreach (var s in notInRuntime) Console.WriteLine("  " + s);

// ----------------------------------------------------------------------
// ExportStubs.g.cs

var stubs = new StringBuilder();
var sreg = new StringBuilder();
int n = 0;
foreach (var (sym, declName) in exports)
{
    if (!decls.TryGetValue(declName, out var d)) { Console.WriteLine($"no IR for export {sym} ({declName})"); continue; }
    var tys = Arr(lean_ctor_get(d, 1)).Select(p => Ty(lean_ctor_get(p, 1))).Where(t => t != "void").ToList();
    var ret = Ty(lean_ctor_get(d, 2));
    if (tys.Concat(new[] { ret }).Any(t => Cs(t) == null)) { Console.WriteLine($"skipping export {sym}: unsupported signature"); continue; }
    var id = "s_" + n++;
    var pars = string.Join(", ", tys.Select((t, k) => $"{Cs(t)} a{k}"));
    var vals = string.Concat(tys.Select((t, k) => ", " + ToValue(t, "a" + k)));
    stubs.Append($"    static Fn {id};\n");
    stubs.Append($"    static {Cs(ret)} {sym}({pars}) => {FromValue(ret, $"Invoke(ref {id}, \"{sym}\"{vals})")};\n");
    sreg.Append($"        LeanExports.Register(\"{sym}\", (nint)(delegate*<{string.Join(", ", tys.Select(Cs).Append(Cs(ret)))}>)&{sym});\n");
}
File.WriteAllText(Path.Combine(outDir, "ExportStubs.g.cs"), $$"""
    // <auto-generated by tools/GenTables/>
    // Entry points for the Lean functions exported with `@[export]` (C ABI: the parameters that are not
    // `void`), generated from the `exportAttr` entries and the IR of the sysroot. The runtime and the
    // kernel call them through `LeanExports`; each one runs the exported declaration with the interpreter.

    using LeanInterpreter.Runtime;

    namespace LeanInterpreter.Interp;

    internal static unsafe partial class ExportStubs
    {
        public static void RegisterAll()
        {
    {{sreg}}    }

    {{stubs}}}

    """.Replace("\r\n", "\n"));
Console.WriteLine($"{n} exports");
return 0;

// ----------------------------------------------------------------------

static IEnumerable<(string Ext, Obj[] Entries)> Entries(Obj moduleData) =>
    Arr(lean_ctor_get(moduleData, 4)).Select(e => (Name(lean_ctor_get(e, 0)), Arr(lean_ctor_get(e, 1))));

static Obj[] Arr(Obj a) => ((ArrayObj)a).m_data.Take((int)((ArrayObj)a).m_size).ToArray();

static string Name(Obj n)
{
    if (lean_is_scalar(n)) return "";
    var p = Name(lean_ctor_get(n, 0));
    var f = lean_ctor_get(n, 1);
    var c = lean_obj_tag(n) == 1 ? lean_string_to_net(f) : lean_unbox(f).ToString();
    return p.Length == 0 ? c : p + "." + c;
}

// `ExternAttrData` is a trivial structure: its `entries : List ExternEntry`
static string ExternSymbol(Obj l)
{
    for (; !lean_is_scalar(l); l = lean_ctor_get(l, 1))
    {
        var e = lean_ctor_get(l, 0);
        if (lean_is_scalar(e) || lean_obj_tag(e) != 2) continue; // standard (backend, fn)
        var backend = Name(lean_ctor_get(e, 0));
        if (backend is "c" or "all") return lean_string_to_net(lean_ctor_get(e, 1));
    }
    return null;
}

static string Ty(Obj t) => lean_is_scalar(t)
    ? new[] { "f64", "u8", "u16", "u32", "u64", "usize", "irr", "obj", "tobj", "f32", "struct", "union", "tagged", "void" }[lean_unbox(t)]
    : "struct";

static string Cs(string t) => t switch
{
    "obj" or "tobj" or "tagged" or "irr" => "Obj", "u8" => "byte", "u16" => "ushort", "u32" => "uint",
    "u64" or "usize" => "ulong", "f64" => "double", "f32" => "float", _ => null,
};

static string ToValue(string t, string v) => t switch
{
    "f64" => $"Value.FromFloat({v})", "f32" => $"Value.FromFloat32({v})", "u8" or "u16" or "u32" or "u64" or "usize" => $"Value.Num({v})", _ => $"Value.Of({v})",
};

static string FromValue(string t, string v) => t switch
{
    "f64" => $"{v}.Float", "f32" => $"{v}.Float32", "u8" or "u16" or "u32" or "u64" or "usize" => $"({Cs(t)}){v}.N", _ => $"{v}.O",
};

static string Unsigned(string t) => t switch { "u8" => "byte", "u16" => "ushort", "u32" => "uint", "u64" or "usize" => "ulong", _ => null };

static string Conv(string irTy, Type t, string v)
{
    if (irTy is "obj" or "tobj" or "tagged") return t == typeof(Obj) ? $"{v}.O" : null;
    if (Unsigned(irTy) is string u)
    {
        if (t == typeof(bool)) return $"{v}.N != 0";
        if (t.IsPrimitive && t != typeof(double) && t != typeof(float)) return $"({CsName(t)})({u}){v}.N";
        return null;
    }
    if (irTy == "f64") return t == typeof(double) ? $"{v}.Float" : null;
    if (irTy == "f32") return t == typeof(float) ? $"{v}.Float32" : null;
    return null;
}

static string Ret(string irTy, Type t, string call)
{
    if (irTy is "obj" or "tobj" or "tagged") return t == typeof(Obj) ? $"Value.Of({call})" : null;
    if (Unsigned(irTy) is string u)
    {
        if (t == typeof(bool)) return $"Value.Num({call} ? 1UL : 0UL)";
        if (t.IsPrimitive && t != typeof(double) && t != typeof(float)) return $"Value.Num(({u}){call})";
        return null;
    }
    if (irTy == "f64") return t == typeof(double) ? $"Value.FromFloat({call})" : null;
    if (irTy == "f32") return t == typeof(float) ? $"Value.FromFloat32({call})" : null;
    return null;
}

static string CsName(Type t) => t == typeof(byte) ? "byte" : t == typeof(ushort) ? "ushort" : t == typeof(uint) ? "uint"
    : t == typeof(ulong) ? "ulong" : t == typeof(sbyte) ? "sbyte" : t == typeof(short) ? "short" : t == typeof(int) ? "int"
    : t == typeof(long) ? "long" : t == typeof(nuint) ? "nuint" : "nint";
